AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint using Amazon API Gateway.
Globals:
  Function:
    Runtime: python3.9
    MemorySize: 128
    Environment:
      Variables:
        TABLE_NAME: !Ref Table
        REGION_NAME: !Ref AWS::Region
Resources:
  microservicehttpendpointpython3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: ./src/
      Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint using Amazon API Gateway.
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ID
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1